- name: Installing Zabbix-agent2 on CentOS
  yum:
    name: zabbix-agent2
    state: latest
  when: ansible_distribution == "CentOS"
  notify: clean yum metadata

- name: Installing Zabbix-agent2 on Debian"
  apt:
    name: zabbix-agent2
    state: latest
  when: ansible_distribution == "Debian"
  notify: clean apt metadata

- name: Placing Zabbix config file
  template:
    src: "zabbix_agent2-conf.j2"
    dest: "/etc/zabbix/zabbix_agent2.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart zabbix agent