- name: restart zabbix agent
  systemd_service:
    enabled: true
    state: restarted
    daemon_reload: true
    name: zabbix-agent2

- name: clean yum metadata
  command: yum clean metadata

- name: clean apt metadata
  command: apt-get clean